### ISSUE TITLE
How did you get the dynamic objects ROIs?

### ISSUE THREAD

**Issue by Jeffwang87** [HaozhiQi/RPIN#4]
Hi,

Thanks for sharing your work. I am wondering how did you get the dynamic objects ROIs. It seems like from PHYRE API, they output info about both dynamic and static objects in random order. Did you manually label the dynamic objects ROIs?

**Comment by HaozhiQi** [comment]
Hi,

Thank you for your interest. For the PHYRE environment, you may want to take a look at the `simulation.featurized_objects` and the `phyre.objects_util.featurized_objects_vector_to_raster` functions, which provide the object identity of dynamic objects.

Specifically, I [set need_featurized_objects=True](https://github.com/HaozhiQi/RPIN/blob/master/rpin/datasets/phyreo.py#L65). Then I get the `sim.featurized_objects.features` and [get the dynamic objects in the scene](https://github.com/HaozhiQi/RPIN/blob/master/rpin/datasets/phyreo.py#L70) via color cue. It will return an array with shape (time_step, num_objects, feature_dimension). And in this array, the order is not random.

After I get this array, I render the image [for each object to get the mask](https://github.com/HaozhiQi/RPIN/blob/master/rpin/datasets/phyreo.py#L105).

There is another trick called [simple_parse](https://github.com/HaozhiQi/RPIN/blob/master/rpin/datasets/phyreo.py#L79). If the objects' color is unique for the scene, we can just use their color as the identity. In this case it calculates faster because we don't need to render the image from object feature.

**Comment by Jeffwang87** [comment]
Got it! Thanks
